### DISCUSSION TITLE
ADR: Utiliser l'attribut `if`d'OpenApi 3.1

### DISCUSSION THREAD

**Discussion by ggrebert** [before-interop/common#2] [Polls]
OpenApi 3.1 permet de conditionner des règles.
Certes, c'est très pratique (ex: conditionner l'obligation de renseigner `statusChangeDetails`),
mais l'application de rendu SWAGER ne gère pas (pour le moment) cet attribut et l'affichage web peut porter à confusion.

Exemple:

```yaml
AnomalieAdresseBase:
  allOf:
    - $ref: https://raw.githubusercontent.com/before-interop/common/main/common/schemas/TroubleTicket.openapi.yaml#/components/schemas/TroubleTicket
    - if:
        properties:
          status:
            pattern: ^(PENDING|RESOLVED|REJECTED|CANCELED)$
      then:
        required:
          - statusChangeReason
    - if:
        properties:
          status:
            const: REJECTED
          statusChangeReason:
            pattern: ^(ALREADY_RESOLVED|DUPLICATE|INVALID|OTHER)$
      then:
        required:
          - statusChangeDetails
    - if:
        properties:
          status:
            const: CANCELED
      then:
        required:
          - statusChangeDetails
  required:
    - code_oi
    - code_oc
    - "@type"
  properties:
    "@baseType":
      const: AnomalieAdresse
    "@type":
      type: string
      readOnly: false
    status:
      description: Le status du ticket.
      default: ACKNOWLEDGED
      enum:
        - ACKNOWLEDGED
        - IN_PROGRESS
        - PENDING
        - RESOLVED
        - CLOSED
        - REJECTED
        - CANCELED
    statusChangeReason:
      enum:
        - ALREADY_RESOLVED
        - DELAY_ANSWER_EXPIRED
        - DELAY_CREATION_EXPIRED
        - DELAY_VALIDATION_EXPIRED
        - DUPLICATE
        - INVALID
        - OTHER
        - RESOLUTION_ACCEPTED
        - UNKNOWN_RESOURCE
        - UNKNOWN_ZONE
        - PASSED_TO_INPROGRESS
        - WAITING_INFORMATION
    expectedResolutionDate:
      description: Date prévisionnelle de résolution du ticket.
        La valeur est renseignée par l'OI lors du passage à l'état `IN_PROGRESS`.
  ...
```

Voici le rendu qui n'a rien à voir:

![image](https://github.com/before-interop/common/assets/1737774/bcd17cb7-df64-4ae3-9992-ea9ae7b7d1c3)
